config/routes.rb
LeagueEngine::Application.routes.draw do
  namespace "admin" do
    resources :leagues
    resources :games
  end

  resources :accounts, :only => [:new, :create]
  resources :user_sessions
  resources :users

  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'

  match 'login' => 'user_sessions#new', :as => 'login'
  match 'logout' => 'user_sessions#destroy', :as => 'logout'
  match 'signup' => 'accounts#new', :as => 'signup'
  #root :to => 'welcome#index'
end

app/models/league.rb
class League < ActiveRecord::Base
  belongs_to :account
  has_many :stats, :class_name => 'LeagueStat', :dependent => :destroy
  has_many :stat_types, :through => :stats
  has_many :teams, :dependent => :destroy
  has_many :games, :dependent => :destroy

  scope :default, :conditions =>{:account_id => 1, :name => 'DefaultLeague'}
  scope :latest, :order => :created_at

  def self.default(attributes = {})
    l = League.new({
      :name => 'DefaultLeague'
    }.with_indifferent_access.merge(attributes))

    # BLITZ Review: Defaults?
    if l.account
      #account needs to be set so that we know what league stats
      #we need to create for the default teams
      %w(Australia Brazil China Denmark).each do |team|
        t = Team.new({:name => team})
        l.account.stats.league.each do |stat|
          ls = LeagueStat.new({:stat_type => stat, :value => 0}) 
          # BLITZ Review: is this ok
          l.stats << ls
          t.league_stats << ls
        end
        l.teams << t
      end
    end
    return l
  end

  # BLITZ Review: plenty of duplication between this and self.default
  def new_team_attributes=(attrs)
    attrs.each do |team_attrs|
      t = Team.new({:name => team_attrs[:name]})
      account.stats.league.each do |stat|
       ls = LeagueStat.new({:stat_type => stat, :value => 0}) 
       self.stats << ls
       t.league_stats << ls
      end
      self.teams << t
    end
  end

  def existing_team_attributes=(attrs)
    teams.reject(&:new_record?).each do |team|
      attributes = attrs[team.id.to_s]
      if attributes
        team.update_attributes(attributes)
      else
        teams.delete(team)
      end
    end
  end
end

app/controllers/admin/leagues_controller.rb
class Admin::LeaguesController < Admin::AdminController

  def index
    @leagues = active_account.leagues
    @display_stats = active_account.stats.league_display
    @sorting_stats = active_account.stats.league_sorting

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @leagues }
      format.json  { render :json => @leagues.t_json }
    end
  end

  def new
    @league = League.new(params[:league])
    4.times{ @league.teams.build } if params[:league].blank?
  end

  def create
    league_params = {:account => active_account}.merge(params[:league])
    @league = League.new(league_params)
    if @league.save
      flash[:notice] = "League Created"
      redirect_to :action => "index"
    else
      render :action => :new
    end # begin
  end #def create

  def show
    @league = League.find(params[:id])
  end

  def edit
    @league = League.find(params[:id])
    @teams = @league.teams.all(:order => 'name')
  end

  def update
    @league = League.find(params[:id])
    if @league.update_attributes(params[:league])
      flash[:notice] = "League Updated"
      redirect_to :action => "index"
    else
      flash[:notice] = "League Updated"
      redirect_to @league 
    end
  end

  def destroy
    if request.post?
      @league = League.find(params[:id])
      @league.clean_delete(@league)
    end
    redirect_to(:action => :list)
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/admin/leagues/_form.html.haml
-form_for ['admin', @league] do |l|
  = render "shared/error_messages", :target => @league
  %label{ :for=>'league_name'}
    League name
  =l.text_field :name

  #teams
    %label
      Teams
    - teams = @teams || @league.teams
    = render :partial => 'fteam', :collection => teams
  = button_to_add( Team, 'fteam')

  .btns
    - btn_txt = request.path =~ /new/ ? 'Create League' : 'Update League'
    = submit_tag btn_txt
    = link_to 'Cancel', admin_leagues_path, :class => 'cancel'

app/views/admin/leagues/_fteam.html.haml
.team
  - new_or_existing = fteam.new_record? ? 'new' : 'existing' 
  - prefix = "league[#{new_or_existing}_team_attributes][]" 
  = fields_for prefix, fteam do |f| 
    = f.text_field :name, :class => 'team_name'
    = button_to_remove(Team , :new_object => fteam.id.nil?)

app/views/admin/leagues/_league.html.haml
%table.greentable
  %thead
    %tr
      %th
        Team
      - @display_stats.each do |stat|
        %th
          = stat.short_desc.capitalize
  %tbody
    = render(:partial => 'team', :collection => league.teams.ordered(@sorting_stats))

app/views/admin/leagues/edit.html.haml
#edit_admin_league.league_form.white_box
  %h3 
    Edit League
  = render :partial => 'form'

app/views/admin/leagues/index.html.erb
<ul class="ListOfLeagues">
<% for league in @leagues -%>
  <li>
	<div class="listblock">
	  <h3 class="leagueListHeader"><%= league.name %></h3>
	  <%= render(:partial => "league_list", :locals => { :league => league })%>
	  <%= link_to 'edit', edit_league_path(league)%>
	</div>
  </li>
<% end %>
</ul>
<div style="clear:both"></div>

app/views/admin/leagues/new.html.erb
<h3>New league</h3>
<p class="error"><%= error_messages_for :league %></p>

<% form_for @league do |form| %>
<fieldset>
	<label for="league_name">League name</label>
	<%=form.text_field :name, :size=>35 %>
</fieldset> 
<%= submit_tag "Create league" %> 
<%= link_to 'Back', :action => 'list' %>
<% end %>

app/views/admin/leagues/new.html.haml
#new_admin_league.league_form.white_box
  %h3 
    New League
  = render :partial => 'form'

app/views/admin/leagues/x__league.html.erb
<table class="greentable">
  <thead>
   <tr>
	  <th>Team</th>
<%  for stat in league.ordered_league_stats  -%>
    <th><%=stat.tag.capitalize -%></th>
<% end %>
    </tr>
  </thead>

   <tbody>     
<% for item in league.league_lists.sort_by {|league_list| [-league_list.sort_val, league_list.team.name]} -%> <!--  -->
	<%= render(:partial => "league_list_row", :locals => { :item => item })%>
<% end %>
  </tbody> 
</table>
<br />

app/views/admin/leagues/x__league_list_row_edit.html.erb
<tr class="<%= cycle('odd', 'even')%>"> 
  <td scope="row" class="left">
    <%= link_to item.team.name, edit_team_path(item.team) -%>
  </td>
    <% for stat in item.league.ordered_league_stats-%>
      <td><%= item.stats[stat.name] -%></td>
    <% end %>
  <td class="extend">
  <a href='<%= url_for confirm_destroy_team_path(item.team) %>' id='<%= item.team.id%>' class='ui-icon ui-icon-trash LeagueTeamDestroy'>Delete</a>
  </td>
</tr>

app/views/admin/leagues/x_add_team.html.erb
<% puts "<p>"+flash[:notice]+"</p>" if flash[:notice] %> </p>
<% form_for :team, :url => { :action => :add_team } do |form| %>
<fieldset>
	<h3>Add team</h3>
  <%= render :partial => 'shared/team_form', :locals => { :form => form } %>
</fieldset> 
<%= submit_tag "Add team" %> 
	<% if @team.league_id %>
		<%= link_to 'Back', :action => 'list', :id => @team.league_id %>
	<% else%>
		<%= link_to 'Back', :action => 'list' %>
	<% end%>
<% end %>

app/views/admin/leagues/x_index.html.erb
<ul class="ListOfLeagues">
<% for league in @leagues -%>
  <li>
	<div class="listblock">
	  <h3 class="leagueListHeader"><%= league.name %></h3>
	  <%= render(:partial => "league_list", :locals => { :league => league })%>
	  <%= link_to 'edit', edit_league_path(league)%>
	</div>
  </li>
<% end %>
</ul>
<div style="clear:both"></div>

app/views/admin/leagues/x_league_action.html.erb
<%= debug(params) %>

app/views/admin/leagues/x_new.html.erb
<h3>New league</h3>
<p class="error"><%= error_messages_for :league %></p>

<% form_for @league do |form| %>
<fieldset>
	<label for="league_name">League name</label>
	<%=form.text_field :name, :size=>35 %>
</fieldset> 
<%= submit_tag "Create league" %> 
<%= link_to 'Back', :action => 'list' %>
<% end %>

app/views/admin/leagues/x_show.html.erb
<%= render(:partial => "league_list", :locals => { :league => @league })%>