config/routes.rb
LeagueEngine::Application.routes.draw do
  namespace "admin" do
    resources :leagues
    resources :games
  end

  resources :accounts, :only => [:new, :create]
  resources :user_sessions
  resources :users

  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'

  match 'login' => 'user_sessions#new', :as => 'login'
  match 'logout' => 'user_sessions#destroy', :as => 'logout'
  match 'signup' => 'accounts#new', :as => 'signup'
  #root :to => 'welcome#index'
end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title
      LeagueEngine - #{controller.controller_name.capitalize}

    -# included javascripts at bottom
    = stylesheet_link_tag     '/javascripts/plugins/jquery-ui/smoothness/jquery-ui-1.7.2.custom.css', :media => "screen"
    = stylesheet_link_tag     'application'
  %body
    - if current_user
      #top_menu
        -# = link_to "Logout", user_session_path, :method => :destroy, :confirm => "Are you sure you want to logout?"
        = link_to 'Logout', logout_path, :confirm => 'Are you sure you want to logout?', :method => :delete
      #menu
        %ul
          %li
            = link_to 'leagues', admin_leagues_path
            %ul
              %li
                = link_to 'new league', new_admin_league_path
          %li
            = link_to 'games', admin_games_path
            %ul
              %li
                = link_to 'new games', new_admin_game_path
          %li
            =# link_to 'players', admin_players_path
            %ul
              %li
                =# link_to 'players stats', admin_players_stats_path

    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}"

    #admin_content
      = yield

    -# --------------------
    -# JS includes
    -# --------------------
    = javascript_include_tag  'jquery-1.4.2'
    = javascript_include_tag  'plugins/jquery-ui/jquery-ui-1.7.2.custom.min.js'
    = javascript_include_tag  'application'
    = yield :javascript
    = javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery?

    -# --------------------
    -# Google Analytics
    -# --------------------
    - unless request.server_name =~ /localhost/
      :javascript
        var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
        document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

        try {
        var pageTracker = _gat._getTracker("UA-2083028-6");
        pageTracker._trackPageview();
        } catch(err) {}

app/views/layouts/application.html.erb
<html>
<head>
  <title>LeagueEngine - <%= controller.controller_name.capitalize %></title>
  
	<%= javascript_include_tag  'jquery-1.4.2' %>
	
	<script src="/javascripts/plugins/jquery-ui/jquery-ui-1.7.2.custom.min.js" type="text/javascript" charset="utf-8"></script>
	<link rel="stylesheet" href="/javascripts/plugins/jquery-ui/smoothness/jquery-ui-1.7.2.custom.css" type="text/css" media="screen" title="no title" charset="utf-8">
	
	<%= stylesheet_link_tag 'back' %>
	<%= javascript_include_tag  'application' %>
	<%= yield :javascript%>
	<%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
</head>
<body>
    <% if current_user%>
		<div id="top_nav">
		  		<!--%= link_to "My Account", account_path %--> |
				<%= link_to "Logout", user_session_path, :method => :destroy %>
		</div>
		
		<div id="menu">
			<ul>
				<li><a href="/leagues">leagues</a>
					<ul>
						<li><a href='/leagues/new'>new league</a></li>
					</ul>
				</li>
				<li>
				  <a href="/games">games</a>
					<ul>
						<li><a href='/games/new'>new game</a></li>
					</ul>
				</li>
				<li>
					<a href="/players">players</a>
			    <ul>
						<li><a href="/players/stats">player stats</a></li>
			    </ul>
			  </li>
			</ul>
		</div>
		<% end %>
		
		<div id="content">
	  	<%- flash.each do |name, msg| -%>
				<%= content_tag :div, msg, :id => "flash_#{name}" %>
			<%- end -%>
	
			<%= yield %>
		</div>
		
		<% if ! request.request_uri.include? 'localhost' %>
		<script type="text/javascript">
		var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
		document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
		</script>
		<script type="text/javascript">
		try {
		var pageTracker = _gat._getTracker("UA-2083028-6");
		pageTracker._trackPageview();
		} catch(err) {}</script>
		<% end %>
</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title 
      LeagueEngine - #{controller.controller_name.capitalize}

    -# included javascripts at bottom  
    = stylesheet_link_tag     '/javascripts/plugins/jquery-ui/smoothness/jquery-ui-1.7.2.custom.css', :media => "screen"
    = stylesheet_link_tag     'application'
  %body
    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}" 

    = yield

    -# --------------------
    -# javascripts 
    -# --------------------
    = javascript_include_tag  'jquery-1.4.2'
    = javascript_include_tag  'plugins/jquery-ui/jquery-ui-1.7.2.custom.min.js'
    = javascript_include_tag  'application'
    = yield :javascript
    = javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery?

    -# --------------------
    -# Google Analytics
    -# --------------------
    - unless request.server_name =~ /localhost/
      :javascript
        var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
        document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

        try {
        var pageTracker = _gat._getTracker("UA-2083028-6");
        pageTracker._trackPageview();
        } catch(err) {}